export const queryKeys = {
     dashboardStats: 'dashboardStats',
     topRecommenders: 'topRecommenders',
     recentRecommendations: 'recentRecommendations',
     allPendingRecommendations: 'allPendingRecommendations',
     viewAllPendingRecommendations: 'viewAllPendingRecommendations',
     viewPendingRecommendations: 'viewPendingRecommendations',
     fetchBusinesses: 'fetchBusinesses',
     fetchSingleBusiness: 'fetchSingleBusiness',
     getRecommendationRequests: 'getRecommendationRequests',
     logout: 'logout',
     sponsor: 'sponsor',
     editSponsor: 'editSponsor',
     cluster: 'cluster',
     editCluster: 'editCluster' ,
     suburb: 'suburb',
     editSuburb: 'editSuburb'  ,  
     clusterDropdown: 'clusterDropdown',
}